---
stages:
  - lint
  - analysis

Ansible Lint:
  stage: lint
  image: sdesbure/ansible-lint
  script:
    - ansible-lint system-setup.yaml

YAML Lint:
  stage: lint
  image: sdesbure/yamllint
  script:
    - yamllint *.y?ml

SonarQube Scan:
  stage: analysis
  image: leppinger/golang-sonarqube-coverage:latest
  script:
    - sonar-scanner
      -D"sonar.projectKey=Ansible"
      -D"sonar.sources=."
      -D"sonar.host.url=https://sonar.thebonds.tech"
      -D"sonar.login=$SONAR_TOKEN"
  only:
    - master
